name: tech subtitles
description: tech. and social stuff.
subtitle: stating the obvious. in tech.
markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /

# Details for the RSS feed generator
url:            ''
author:         'Florian Thiel'
