name: tech subtitles
description: tech. and social stuff.
subtitle: stating the obvious. in tech.
markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /

# Details for the RSS feed generator
url:            'https://noroute.github.io'
author:         'Florian Thiel'
copyright:      'Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.'
